# Generated by Django 2.2.5 on 2019-09-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('html_parser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
